# Generated by Django 3.1 on 2020-08-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarangKeluar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_field', models.DateTimeField(blank=True, db_column='Waktu ', null=True)),
                ('sku', models.TextField(blank=True, db_column='SKU', null=True)),
                ('nama_barang', models.TextField(blank=True, db_column='Nama Barang', null=True)),
                ('jumlah_keluar', models.BigIntegerField(blank=True, db_column='Jumlah Keluar', null=True)),
                ('harga_jual', models.BigIntegerField(blank=True, db_column='Harga Jual', null=True)),
                ('total', models.BigIntegerField(blank=True, db_column='Total', null=True)),
                ('catatan', models.TextField(blank=True, db_column='Catatan', null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BarangMasuk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_field', models.DateTimeField(blank=True, db_column='Waktu ', null=True)),
                ('sku', models.TextField(blank=True, db_column='SKU', null=True)),
                ('nama_barang', models.TextField(blank=True, db_column='Nama Barang', null=True)),
                ('jumlah_pemesanan', models.BigIntegerField(blank=True, db_column='Jumlah Pemesanan', null=True)),
                ('jumlah_diterima', models.BigIntegerField(blank=True, db_column='Jumlah Diterima', null=True)),
                ('harga_beli_field', models.BigIntegerField(blank=True, db_column='Harga Beli ', null=True)),
                ('total', models.BigIntegerField(blank=True, db_column='Total', null=True)),
                ('nomer_kwitansi', models.TextField(blank=True, db_column='Nomer Kwitansi', null=True)),
                ('catatan', models.TextField(blank=True, db_column='Catatan', null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='JumlahBarang',
            fields=[
                ('sku', models.TextField(db_column='SKU', primary_key=True, serialize=False, unique=True)),
                ('nama_item', models.TextField(blank=True, db_column='Nama Item', null=True)),
                ('jumlah_sekarang', models.BigIntegerField(blank=True, db_column='Jumlah Sekarang', null=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
