# Generated by Django 3.1 on 2020-08-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaporanNilaiBarang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.TextField(blank=True, db_column='SKU', null=True)),
                ('nama_item', models.TextField(blank=True, db_column='Nama Item', null=True)),
                ('jumlah', models.BigIntegerField(blank=True, db_column='Jumlah', null=True)),
                ('rata_harga_beli', models.BigIntegerField(blank=True, db_column='Rata-Rata Harga Beli', null=True)),
                ('total', models.BigIntegerField(blank=True, db_column='Total', null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LaporanPenjualan',
            fields=[
                ('id_pesanan', models.TextField(db_column='ID Pesanan', primary_key=True, serialize=False, unique=True)),
                ('waktu_field', models.DateTimeField(blank=True, db_column='Waktu ', null=True)),
                ('sku', models.TextField(blank=True, db_column='SKU', null=True)),
                ('nama_barang', models.TextField(blank=True, db_column='Nama Barang', null=True)),
                ('jumlah', models.BigIntegerField(blank=True, db_column='Jumlah', null=True)),
                ('harga_jual', models.BigIntegerField(blank=True, db_column='Harga Jual', null=True)),
                ('total', models.BigIntegerField(blank=True, db_column='Total', null=True)),
                ('harga_beli', models.BigIntegerField(blank=True, db_column='Harga Beli', null=True)),
                ('laba', models.BigIntegerField(blank=True, db_column='Laba', null=True)),
            ],
        ),
    ]
