# Generated by Django 3.1 on 2020-08-18 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_laporannilaibarang_laporanpenjualan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laporanpenjualan',
            options={'managed': True},
        ),
    ]
