# Generated by Django 3.1 on 2020-08-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200818_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangkeluar',
            name='harga_jual',
            field=models.DecimalField(blank=True, db_column='Harga Jual', decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='barangkeluar',
            name='total',
            field=models.DecimalField(blank=True, db_column='Total', decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='barangmasuk',
            name='harga_beli_field',
            field=models.DecimalField(blank=True, db_column='Harga Beli ', decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='barangmasuk',
            name='total',
            field=models.DecimalField(blank=True, db_column='Total', decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='laporannilaibarang',
            name='rata_harga_beli',
            field=models.DecimalField(blank=True, db_column='Rata-Rata Harga Beli', decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='laporannilaibarang',
            name='total',
            field=models.DecimalField(blank=True, db_column='Total', decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='laporanpenjualan',
            name='harga_beli',
            field=models.DecimalField(blank=True, db_column='Harga Beli', decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='laporanpenjualan',
            name='harga_jual',
            field=models.DecimalField(blank=True, db_column='Harga Jual', decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='laporanpenjualan',
            name='laba',
            field=models.DecimalField(blank=True, db_column='Laba', decimal_places=5, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='laporanpenjualan',
            name='total',
            field=models.DecimalField(blank=True, db_column='Total', decimal_places=5, max_digits=19, null=True),
        ),
    ]
