# Generated by Django 3.1 on 2020-08-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200818_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laporanpenjualan',
            name='id_pesanan',
            field=models.TextField(blank=True, db_column='ID Pesanan', primary_key=True, serialize=False, unique=True),
        ),
    ]
